spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000ms
    password:
    jedis:
      pool:
        max-active: 10
        max-wait: -1ms
        min-idle: 0





## mybatis-plus 信息配置
mybatis-plus:
  check-config-location: true
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.lin.learn.survivor.common.entity
  global-config:
    id-type: 1
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: true
